# 대여 제한
BOOK_NUM_PER_ONE = 3
DAYS_OF_RENTAL = 31

# 날짜 포맷
DATE_FORMAT = "%Y-%m-%d"

# 로그 분류
RENT_BOOK = "RENT_BOOK"
RETURN_BOOK = "RETURN_BOOK"
CHECK_USER = "CHECK_USER"
CHECK_BOOK = "CHECK_BOOK"
CHECK_IMMINENT_USER = "CHECK_IMMINENT_USER"
CHECK_OVERDUE_USER = "CHECK_OVERDUE_USER"
GET_BOOK_LIST = "GET_BOOK_LIST"

# 로그 포맷
LOG_FORMAT = "[<DATE>] <TYPE> : <RESULT> (<DETAIL>)"